apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: frontend
spec:
  targetnamespace: frontend
  interval: 10m
  path: "./kustomize/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  healthChecks:
    - apiVersion: flagger.app/v1beta1
      kind: Canary
      name: podinfo
      namespace: frontend
